apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: imagetwotire.azurecr.io/two-tireapplication_frontend-service:latest
          ports:
            - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: LoadBalancer

